name: Budowanie i Wysyłanie

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  budowanie:
    runs-on: windows-latest

    steps:
      - name: Sprawdź repozytorium
        uses: actions/checkout@v2

      - name: Skonfiguruj Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Zainstaluj zależności
        run: pip install -r requirements.txt

      - name: Zbuduj plik wykonywalny
        run: pyinstaller --onefile project.py

      - name: Prześlij artefakt
        uses: actions/upload-artifact@v2
        with:
          name: projekt-exe
          path: dist/project.exe
